language: php

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

  matrix:
  include:
    - php: 7.4snapshot
      env: WP_TRAVISCI=test-php
    - php: 7.3
      env: WP_TRAVISCI=test-php
    - php: 7.2
      env: WP_TRAVISCI=test-php
    - php: 7.2
      env: WP_TRAVISCI=test-js
    - php: 7.2
      env: WP_TRAVISCI=lint
    - php: 7.3
      env: WP_TRAVISCI=test-e2e

# Make sure NodeGit gets the correct C libs, copied from Gutenberg.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

before_install:
  - |
    if [[ "$WP_TRAVISCI" == "test-e2e" ]] ; then
      # Upgrade docker-compose, copied from Gutenberg.
      sudo rm /usr/local/bin/docker-compose
      curl -sL https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64 > docker-compose
      chmod +x docker-compose
      sudo mv docker-compose /usr/local/bin
    fi

install:
  - composer install
  - nvm install --lts
  - npm install
  - npm run build

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

script:
  - |
    if [[ "$WP_TRAVISCI" == "test-php" ]] ; then
      npm run test:php
    elif [[ "$WP_TRAVISCI" == "test-js" ]] ; then
      npm run test:js
    elif [[ "$WP_TRAVISCI" == "lint" ]] ; then
      npm run lint:php
      npm run lint:js
      npm run lint:pkg-json
    elif [[ "$WP_TRAVISCI" == "test-e2e" ]] ; then
      npm run env start
      npm run test:e2e
    fi
